[global]
	crash reports = off

[web]
	# Do not bind to all interfaces.
	bind to = 127.0.0.1

[plugin:proc:diskspace]
	# Added: /dev /host/proc/* /host/sys/* /host/run/user/* /mnt.
	exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/* /dev /host/proc/* /host/sys/* /host/run/user/* /mnt
	# Added: devtmpfs hugetlbfs ramfs.
	exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs devtmpfs hugetlbfs ramfs
	# "auto" fails to detect: /host/run.
	space usage for all disks = yes
