#!/usr/bin/env bash
#MISE description="Test docker compose build for changed or all servers"
#USAGE arg "[server]" help="Server to build"
#USAGE complete "server" run="ls -1d srv/*/ | xargs -n 1 basename"
server="${usage_server:-}"

set -euo pipefail

if [[ -n $server ]]; then
    printf "Testing server %q\n" "$server"
    CHANGED="srv/$server"
elif [[ ${EVENT_NAME:-} == "pull_request" ]]; then
    printf "Testing servers changed by PR (PR_BASE_SHA=%s PR_SHA=%s)\n" "$PR_BASE_SHA" "$PR_SHA"
    CHANGED=$(git diff --name-only "$PR_BASE_SHA"..."$PR_SHA" | awk -F/ '/^srv\/[^/]+\//{print $1"/"$2}' | sort -u)
else
    printf "Testing all servers\n"
    CHANGED=$(find srv -mindepth 1 -maxdepth 1 -type d)
fi

for SRV in $CHANGED; do
    printf "\nBuilding %q\n\n" "$SRV"
    pushd "$SRV" >/dev/null

    # Generate fnox.local.toml with fake secrets in the "test" profile.
    # On the server, ../../fnox.toml is deployed as fnox.local.toml instead.
    if [[ -f fnox.toml ]]; then
        {
            echo '# Auto-generated by test:docker-build. Do not edit.'
            echo '# On the server, ../../fnox.toml is deployed as fnox.local.toml instead.'
            echo '[profiles.test.secrets]'
            grep -oP '^\s*\K[A-Z_]+(?=\s*=)' fnox.toml | while read -r key; do
                printf '%s = { default = "fake" }\n' "$key"
            done
        } >fnox.local.toml
    fi

    FNOX_PROFILE="test" mise exec -- docker compose build

    popd >/dev/null
done
