## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/plugin/go.d/collector/dnsquery#readme

jobs:
  - name: example.com NS
    record_types:
      - A
    domains:
      - example.com
    servers:
      - a.ns.example.com
      - b.ns.example.com
