## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/plugin/go.d/collector/filecheck#readme

update_every: 30

jobs:
  - name: apt_status
    files:
      include:
        - /host/run/reboot-required
        - /host/var/lib/apt/periodic/update-success-stamp
