## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/plugin/go.d/collector/dnsquery#readme

jobs:
  - name: example.com NS
    record_types:
      - A
    domains:
      - example.com
    servers:
      - a.ns.example.com
      - b.ns.example.com

  - name: example.com
    record_types:
      - A
    domains:
      - example.com
    servers:
      - 1.1.1.1
      - 8.8.8.8

  - name: primary.example.com
    record_types:
      - A
    domains:
      - primary.example.com
    servers:
      - 1.1.1.1
      - 8.8.8.8

  - name: secondary.example.com
    record_types:
      - A
    domains:
      - secondary.example.com
    servers:
      - 1.1.1.1
      - 8.8.8.8

  - name: example.com MX
    record_types:
      - MX
    domains:
      - example.com
    servers:
      - 1.1.1.1
      - 8.8.8.8
