## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/plugin/go.d/collector/prometheus#readme

jobs:
  - name: postfix
    url: http://127.0.0.1:9154/metrics

  - name: backup
    url: file:///prom/backup.prom
