#!/usr/bin/env bash
#MISE description="Deploy a server"
#USAGE arg "server" help="Server to deploy"
#USAGE complete "server" run="ls -1d srv/*/ | xargs -n 1 basename"
server="${usage_server:?}"

set -euo pipefail

die() {
    echo "$@"
    exit 1
}

proj="srv/$server"
destination="$(cat "$proj/destination")"
test -n "$destination" || die "file is empty: $proj/destination"
test -f "$proj/docker-compose.yml" || die "No such file: $proj/docker-compose.yml"

# For servers with secrets, provide age key.
if [[ -f "$proj/fnox.toml" ]]; then
    # Send FNOX_AGE_KEY via SSH env so the server can decrypt secrets with mise/fnox.
    # Requires AcceptEnv FNOX_AGE_KEY in the server's sshd config.
    FNOX_AGE_KEY=$(grep AGE-SECRET-KEY ~/.config/fnox/age.txt)
    export FNOX_AGE_KEY
fi

# Snapshot current compose image IDs before syncing the new yml,
# so we can clean up old images (e.g. previous version of ollama) after deploy.
# docker rmi safely refuses to remove images still in use by running containers.
old_images=$(ssh -o ControlPath=none -o SendEnv=FNOX_AGE_KEY "${destination}" \
    'cd ~/.myserver && PATH="$HOME/.local/bin:$PATH" mise exec -- docker compose images -q 2>/dev/null' | tr '\n' ' ' || true)
trap 'ssh "${destination}" "docker rmi $old_images 2>/dev/null || true"' EXIT

echo "==> Syncing $server → $destination..."
rsync --info=progress2 --recursive --links --mkpath --delete --delete-excluded \
    --cvs-exclude --exclude="*.local.toml" \
    "./$proj/" "${destination}:.myserver"
# If a shared root fnox.toml exists, copy it as fnox.local.toml on the server
# to provide provider config absent from the server's own fnox.toml.
# This is safe because $proj/fnox.local.toml is autogenerated and excluded from rsync.
[[ ! -f "$proj/fnox.toml" || ! -f fnox.toml ]] ||
    scp -q fnox.toml "${destination}:.myserver/fnox.local.toml"

echo "==> Deploying on $destination..."
# Use ssh -o ControlPath=none to disable ControlMaster for this command,
# since it can cause issues with environment variable forwarding and concurrent SSH sessions.
# Add ~/.local/bin to PATH in case the server's mise is installed there.
ssh -t -o ControlPath=none -o SendEnv=FNOX_AGE_KEY "${destination}" 'set -euo pipefail
    export PATH="$HOME/.local/bin:$PATH"
    cd ~/.myserver
    mise exec -- docker compose build
    mise exec -- docker compose up --detach --remove-orphans --wait'
