[global]
	crash reports = off

[web]
	# Do not bind to all interfaces.
	# Bind to HOST_GATEWAY_IP to make it accessible from docker network (for Caddy).
	bind to = 127.0.0.1 {{ .Env.HOST_GATEWAY_IP }}

[plugin:proc:diskspace]
	# Added: /dev /host/proc/* /host/sys/* /host/run/user/*.
	exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/* /dev /host/proc/* /host/sys/* /host/run/user/*
	# Added: devtmpfs hugetlbfs ramfs.
	exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs devtmpfs hugetlbfs ramfs
	# "auto" fails to detect: /boot/efi, /host/run, /host/dev/shm, /dev/shm.
	space usage for all disks = yes
